GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/61dee0871851b9917ff2f821

###

DELETE  http://localhost:3001/api/persons/61dee0871851b9917ff2f881

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Nu",
    "number": "181-736411"
}